
server:
  port: 8080
  servlet:
    context-path: /linhong

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/mmall?useUnicode=true&characterEncoding=utf-8
    username: root
    password: 1a2b3c4d

mybatis:
  configuration:
    map-underscore-to-camel-case: true
  mapper-locations:
    classpath:mapper/*.xml
    classpath*:com/**/mapper/*.xml

